/**
 * Development Mode Dummy Data
 * Returns mock data when using placeholder Supabase credentials
 */

export const DEV_CLIENTS = [
  {
    id: '1',
    contact_name: 'James Anderson',
    company_name: 'Highland Estates',
    email: 'james@highlandestates.com',
    phone: '01463 234567',
    address: 'Estate Office, Inverness',
    postcode: 'IV1 1AA',
    county: 'Highlands',
    total_woodland_area: 150.5,
    status: 'active',
    notes: 'Major client - 3 ongoing projects',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    contact_name: 'Sarah MacLeod',
    company_name: 'Perthshire Woodlands Ltd',
    email: 'sarah@perthshirewoodlands.com',
    phone: '01738 445566',
    address: 'Perth Business Park',
    postcode: 'PH1 3BB',
    county: 'Perthshire',
    total_woodland_area: 85.0,
    status: 'active',
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEV_PROJECTS = [
  {
    id: '1',
    client_id: '1',
    project_name: 'Glen Affric Expansion',
    location: 'Glen Affric, Highlands',
    area_hectares: 45.5,
    planting_year: 2024,
    tree_species: ['Scots Pine', 'Birch', 'Rowan'],
    grant_scheme: 'Woodland Creation Grant',
    status: 'in_progress',
    start_date: '2024-03-01',
    completion_date: '2024-11-30',
    total_cost: 125000,
    grant_amount: 75000,
    description: 'Native woodland expansion project',
    notes: 'Planting phase 70% complete',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    client_id: '2',
    project_name: 'Perthshire Valley Restoration',
    location: 'Perth Valley',
    area_hectares: 28.0,
    planting_year: 2024,
    tree_species: ['Oak', 'Ash', 'Hazel'],
    grant_scheme: 'HS2 Woodland Fund',
    status: 'planning',
    start_date: '2025-01-15',
    completion_date: null,
    total_cost: 68000,
    grant_amount: 45000,
    description: 'Ancient woodland restoration',
    notes: 'Awaiting final grant approval',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const DEV_TEAM = [
  {
    id: '1',
    name: 'John Smith',
    role: 'Tree Planting Contractor',
    company_name: 'Highland Trees Ltd',
    email: 'john@highlandtrees.com',
    phone: '07700 900123',
    specializations: ['Tree Planting', 'Ground Preparation'],
    is_active: true,
    availability_status: 'available',
    projects_completed: 15,
    quality_rating: 4.8,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sarah MacLeod',
    role: 'Fencing Specialist',
    company_name: null,
    email: 'sarah@example.com',
    phone: '07700 900456',
    specializations: ['Deer Fencing', 'Stock Fencing'],
    is_active: true,
    availability_status: 'busy',
    projects_completed: 23,
    quality_rating: 4.9,
    created_at: new Date().toISOString(),
  },
]

export const DEV_CONTACTS = [
  {
    id: '1',
    name: 'Robert Campbell',
    email: 'robert@example.com',
    phone: '01463 777888',
    message: 'Interested in woodland establishment for 50 hectares in Morayshire. Please contact to discuss.',
    status: 'new',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Emma Stewart',
    email: 'emma@example.com',
    phone: '07700 123456',
    message: 'Looking for tree planting services for small estate. Need quote.',
    status: 'replied',
    created_at: new Date(Date.now() - 86400000).toISOString(), // Yesterday
  },
]

export const DEV_PHOTOS = [
  {
    id: '1',
    project_id: '1',
    url: '/images/Acer1.jpg',
    storage_path: 'dev/Acer1.jpg',
    caption: 'Tree planting project - Highland estate',
    photo_date: '2024-03-15',
    file_name: 'Acer1.jpg',
    file_size: 2048000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: { name: 'Glen Affric Expansion' },
  },
  {
    id: '2',
    project_id: '1',
    url: '/images/Acer4.jpg',
    storage_path: 'dev/Acer4.jpg',
    caption: 'Professional tree planting team at work',
    photo_date: '2024-04-10',
    file_name: 'Acer4.jpg',
    file_size: 1920000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: { name: 'Glen Affric Expansion' },
  },
  {
    id: '3',
    project_id: '1',
    url: '/images/Acer5.jpg',
    storage_path: 'dev/Acer5.jpg',
    caption: 'Site ground preparation for planting',
    photo_date: '2024-03-20',
    file_name: 'Acer5.jpg',
    file_size: 2100000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: { name: 'Glen Affric Expansion' },
  },
  {
    id: '4',
    project_id: null,
    url: '/images/AcerQuadBike.jpg',
    storage_path: 'dev/AcerQuadBike.jpg',
    caption: 'Forestry quad bike for site access',
    photo_date: '2024-05-12',
    file_name: 'AcerQuadBike.jpg',
    file_size: 1850000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: null,
  },
  {
    id: '5',
    project_id: '2',
    url: '/images/Acer12.jpg',
    storage_path: 'dev/Acer12.jpg',
    caption: 'Saplings with protective guards',
    photo_date: '2024-06-05',
    file_name: 'Acer12.jpg',
    file_size: 1980000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: { name: 'Perthshire Valley Restoration' },
  },
  {
    id: '6',
    project_id: null,
    url: '/images/AcerDeer.jpg',
    storage_path: 'dev/AcerDeer.jpg',
    caption: 'Deer fencing installation for tree protection',
    photo_date: '2024-05-20',
    file_name: 'AcerDeer.jpg',
    file_size: 2200000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: null,
  },
  {
    id: '7',
    project_id: '1',
    url: '/images/Acer18.jpg',
    storage_path: 'dev/Acer18.jpg',
    caption: 'Large scale woodland planting operation',
    photo_date: '2024-04-18',
    file_name: 'Acer18.jpg',
    file_size: 2150000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: { name: 'Glen Affric Expansion' },
  },
  {
    id: '8',
    project_id: null,
    url: '/images/AcerLorry.jpg',
    storage_path: 'dev/AcerLorry.jpg',
    caption: 'Equipment transport and logistics',
    photo_date: '2024-03-08',
    file_name: 'AcerLorry.jpg',
    file_size: 1900000,
    mime_type: 'image/jpeg',
    created_at: new Date().toISOString(),
    projects: null,
  },
]

export const DEV_ANALYTICS = {
  totalProjects: 15,
  activeProjects: 8,
  completedProjects: 7,
  onHoldProjects: 0,
  totalClients: 12,
  activeClients: 10,
  prospectClients: 2,
  revenueThisMonth: 45000,
  revenueLastMonth: 38000,
  newContacts: 3,
  conversionRate: 65,
}

/**
 * Check if we're in dev mode with placeholder Supabase
 */
export function isDevMode() {
  const nodeEnv = process.env.NODE_ENV
  // Check both NEXT_PUBLIC_ and non-public versions
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL
  const hasPlaceholder = supabaseUrl?.includes('placeholder')
  return nodeEnv === 'development' && hasPlaceholder
}
